name: glade_forms
description: A universal way to define form validators with support of translations.
version: 5.1.0
repository: https://github.com/netglade/glade_forms
issue_tracker: https://github.com/netglade/glade_forms/issues
screenshots:
  - description: The glade_forms package logo.
    path: doc/icon.png

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.9.1
  netglade_utils: ^2.4.1
  provider: ^6.0.5

dev_dependencies:
  netglade_analysis: ^18.0.0
  test: ^1.25.8
