name: glade_forms
resolution: workspace
description: A universal way to define form validators with support of translations.
version: 6.0.0
repository: https://github.com/netglade/glade_forms
issue_tracker: https://github.com/netglade/glade_forms/issues

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  clock: ^1.1.1
  collection: ^1.17.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.9.1
  netglade_flutter_utils: ^1.3.0
  netglade_utils: ^2.4.1
  provider: ^6.0.5

dev_dependencies:
  netglade_analysis: ^21.0.0
  test: ^1.25.8
  yaml: ^3.1.2

screenshots:
  - description: The glade_forms package logo.
    path: doc/icon.png
