name: glade_forms_storybook
resolution: workspace
description: Glade Forms - Interactive example
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_hooks: ^0.21.3+1
  flutter_markdown: ^0.7.6
  glade_forms:
    path: ../glade_forms
  provider: ^6.1.2
  widgetbook: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  netglade_analysis: ^21.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - lib/usecases/
    - lib/usecases/dependencies/
    - lib/usecases/onchange/
    - lib/usecases/regress/
