name: glade_forms_devtools_extension
description: A DevTools extension for glade_forms package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  devtools_extensions: ^0.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  glade_forms:
    path: ../glade_forms
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.8
  yaml: ^3.1.2

flutter:
  uses-material-design: true
