name: glade_forms_devtools_extension
resolution: workspace
description: A DevTools extension for glade_forms package
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.10.0"

dependencies:
  devtools_extensions: ^0.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  glade_forms:
    path: ../glade_forms
  multi_split_view: ^3.6.1
  netglade_flutter_utils: ^1.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  netglade_analysis: ^21.0.0
  test: ^1.25.8
  yaml: ^3.1.2

flutter:
  uses-material-design: true
