name: glade_forms_example
resolution: workspace
description: Example project how to use GladeForms
publish_to: none
version: 1.0.1

environment:
  sdk: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  glade_forms:
    path: ../
